//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaIslem
    {
        public int FaturaID { get; set; }
        public string Tckn { get; set; }
        public Nullable<int> EkNo { get; set; }
        public Nullable<int> FaturaTutari { get; set; }
        public Nullable<int> MusteriID { get; set; }
    }
}
