//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HesapIslem
    {
        public int hesapIslemID { get; set; }
        public Nullable<int> hesapID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> ekNO { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> ıslemID { get; set; }
        public Nullable<int> miktar { get; set; }
        public string acıklama { get; set; }
    
        public virtual Hesap Hesap { get; set; }
        public virtual Islem Islem { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
