//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hesap()
        {
            this.EftHavale = new HashSet<EftHavale>();
            this.HesapIslem = new HashSet<HesapIslem>();
        }
    
        public int hesapID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> ekNO { get; set; }
        public Nullable<int> hesapDurum { get; set; }
        public Nullable<System.DateTime> acilisTarihi { get; set; }
        public Nullable<decimal> bakiye { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EftHavale> EftHavale { get; set; }
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HesapIslem> HesapIslem { get; set; }
    }
}
