//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogs()
        {
            this.OgsIslem = new HashSet<OgsIslem>();
        }
    
        public int ogsID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> durum { get; set; }
        public Nullable<decimal> bakiye { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgsIslem> OgsIslem { get; set; }
    }
}
