//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgsIslem
    {
        public int OgsIslemID { get; set; }
        public Nullable<int> ogsID { get; set; }
        public Nullable<int> IslemlerID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> miktar { get; set; }
        public Nullable<int> MusteriID { get; set; }
    
        public virtual Islemler Islemler { get; set; }
        public virtual Ogs Ogs { get; set; }
    }
}
